[package]
name = "pubg-accel-gui"
version.workspace = true
edition.workspace = true

[build-dependencies]
tauri-build = "2"

[dependencies]
tauri = "2"
window-vibrancy = "0.5"
protocol = { path = "../protocol" }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_UI_Shell"] }
